export const ARTICLE_TOKENS = {
  REPO: 'ARTICLE_REPO',
  ARTICLE_N_TYPE_REPO: 'ARTICLE_N_TYPE_REPO',
  ARTICLE_TYPE_REPO: 'ARTICLE_TYPE_REPO',
  ARTICLE_N_ACCESS_REPO: 'ARTICLE_N_ACCESS_REPO',
  ARTICLE_PERMISSION_REPO: 'ARTICLE_PERMISSION_REPO',
  ARTICLE_RATE_REPO: 'ARTICLE_RATE_REPO',
  COMMENT_REPO: 'COMMENT_REPO',
  COMMENT_RATE_REPO: 'COMMENT_RATE_REPO',
};
